apiVersion: v1
kind: Pod
metadata:
  name: task-pv-rbd
spec:
  volumes:
    - name: task-pv-rbd
      persistentVolumeClaim:
        claimName: rook-ceph-rbd
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/ceph"
          name: task-pv-rbd
