apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-rbd
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
