apiVersion: v1
kind: Pod
metadata:
  name: poststart
spec:
  containers:
    - name: lifecycle-demo-container
      image: kanzihuang/alpine:utils
      lifecycle:
        postStart:
          exec:
            command: ["/bin/touch", "/tmp/healthy"]
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 5
